/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pixit.app;

import com.pixit.resource.HomeResource;
import io.dropwizard.Application;
import io.dropwizard.assets.AssetsBundle;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;
import io.dropwizard.views.ViewBundle;

public class PixitApplication extends Application<PixitConfiguration> {

    public static void main(String... args) throws Exception {
        new PixitApplication().run(args);
    }

    @Override
    public void initialize(Bootstrap<PixitConfiguration> bootstrap) {
        bootstrap.addBundle(new ViewBundle<>());
        bootstrap.addBundle(new AssetsBundle("/assets/favicon.ico", "/favicon.ico"));
    }

    @Override
    public void run(PixitConfiguration configuration, Environment environment) throws Exception {
        environment.jersey().register(HomeResource.class);
    }

}
